Uspa.Admin/Controllers/BannersController.cs
using AutoMapper;
using System.Net;
using System.Web.Mvc;
using Uspa.Admin.ViewModel;
using Uspa.Domain.LocalDb;
using Uspa.Domain.Repository.Implementation;
using Uspa.Domain.Repository.Interface;

namespace Uspa.Admin.Controllers
{
    public class BannersController : Controller
    {
        private IBanners bannersHandler = new BannersRepository();
        private ISites sitesHandler = new SitesRepository();

        public ActionResult Index()
        {
            return View(bannersHandler.All());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Banners banners = bannersHandler.GetById(id);

            if (banners == null)
            {
                return HttpNotFound();
            }
            return View(banners);
        }

        public ActionResult Create()
        {
            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,url,state,site_id")] BannersViewModel banner)
        {
            if (ModelState.IsValid)
            {

                Mapper.Initialize(cfg => cfg.CreateMap<BannersViewModel, Banners>());

                Banners banners = Mapper.Map<BannersViewModel, Banners>(banner);

                bannersHandler.Add(banners);
                return RedirectToAction("Index");
            }

            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title", banner.site_id);
            return View(banner);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mapper.Initialize(cfg => cfg.CreateMap<Banners, BannersViewModel>());
            BannersViewModel banner = Mapper.Map<Banners, BannersViewModel>(bannersHandler.GetById(id));


            if (banner == null)
            {
                return HttpNotFound();
            }

            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title", banner.site_id);
            return View(banner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,url,state,site_id")] BannersViewModel banner)
        {
            if (ModelState.IsValid)
            {

                Mapper.Initialize(cfg => cfg.CreateMap<BannersViewModel, Banners>());

                Banners banners = Mapper.Map<BannersViewModel, Banners>(banner);


                bannersHandler.Update(banners);
                return RedirectToAction("Index");
            }

            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title", banner.site_id);
            return View(banner);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banners banner = bannersHandler.GetById(id);

            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Banners banners = bannersHandler.GetById(id);
            bannersHandler.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                sitesHandler.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Uspa.Admin/Controllers/MenusController.cs
using PagedList;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Uspa.Domain.LocalDb;
using Uspa.Domain.Repository.Implementation;
using Uspa.Domain.Repository.Interface;
using Uspa.Domain.Settings;

namespace Uspa.Admin.Controllers
{
    public class MenusController : Controller
    {
        private IMenus menusHandler = new MenusRepository();
        private IMenuTypes menutypesHandler = new MenuTypesRepository();
        private ISites sitesHandler = new SitesRepository();
        private IContents _contentsHandler = new ContentRepository();

        public ActionResult Index(int? page, string search, int? menuType)
        {
            var menus = menusHandler.All();

            //filter
            if (menuType != null && menuType != 0)
                menus = menus.Where(m => m.menuType_id == menuType);

            List<MenuTypes> menuTypes = new MenuTypesRepository().All().ToList();
            menuTypes.Insert(0, new MenuTypes { id = 0, title = "All" });
            ViewBag.MenuType = new SelectList(menuTypes, "id", "title");

            //serch
            menus = menusHandler.Search(menus, search);

            int pageSize = PagingSettings.PageSizeInMenu;
            int pageNumber = (page ?? 1);
            return View(menus.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Menus menus = menusHandler.GetById(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            return View(menus);
        }

        public ActionResult Create()
        {
            ViewBag.сontent_id = new SelectList(_contentsHandler.All(), "id", "title");
            ViewBag.menuType_id = new SelectList(menutypesHandler.All(), "id", "title");
            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,previd,parentidPrev,parentid,title,state,menuType_id,site_id,сontent_id")] Menus menus)
        {
            if (ModelState.IsValid)
            {
                menusHandler.Add(menus);
                return RedirectToAction("Index");
            }

            ViewBag.сontent_id = new SelectList(_contentsHandler.All(), "id", "title", menus.сontent_id);
            ViewBag.menuType_id = new SelectList(menutypesHandler.All(), "id", "title", menus.menuType_id);
            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title", menus.site_id);
            return View(menus);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = menusHandler.GetById(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            ViewBag.сontent_id = new SelectList(_contentsHandler.All(), "id", "title", menus.сontent_id);
            ViewBag.menuType_id = new SelectList(menutypesHandler.All(), "id", "title", menus.menuType_id);
            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title", menus.site_id);
            return View(menus);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,previd,parentidPrev,parentid,title,state,menuType_id,site_id,сontent_id")] Menus menus)
        {
            if (ModelState.IsValid)
            {
                menusHandler.Update(menus);
                return RedirectToAction("Index");
            }
            ViewBag.сontent_id = new SelectList(_contentsHandler.All(), "id", "title", menus.сontent_id);
            ViewBag.menuType_id = new SelectList(menutypesHandler.All(), "id", "title", menus.menuType_id);
            ViewBag.site_id = new SelectList(sitesHandler.All(), "id", "title", menus.site_id);
            return View(menus);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = menusHandler.GetById(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            return View(menus);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            menusHandler.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                menusHandler.Dispose();
                menutypesHandler.Dispose();
                sitesHandler.Dispose();
                _contentsHandler.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Uspa.Admin/Controllers/SitesController.cs
using System.Net;
using System.Web.Mvc;
using Uspa.Domain.LocalDb;
using Uspa.Domain.Repository.Implementation;
using Uspa.Domain.Repository.Interface;

namespace Uspa.Admin.Controllers
{
    public class SitesController : Controller
    {
        private ISites sitesHandler = new SitesRepository();
        private ILanguages languagesHandler = new LanguagesRepository();

        public ActionResult Index()
        {
            var sites = sitesHandler.All();
            return View(sites);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sites site = sitesHandler.GetById(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            return View(site);
        }

        public ActionResult Create()
        {
            ViewBag.language_id = new SelectList(languagesHandler.All(), "id", "title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,countContent,language_id")] Sites site)
        {
            if (ModelState.IsValid)
            {
                if (site.countContent >= 0)
                {
                    sitesHandler.Add(site);
                    return RedirectToAction("Index");
                }
            }

            ViewBag.language_id = new SelectList(languagesHandler.All(), "id", "title", site.language_id);
            return View(site);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sites site = sitesHandler.GetById(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            ViewBag.language_id = new SelectList(languagesHandler.All(), "id", "title", site.language_id);
            return View(site);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,countContent,language_id")] Sites site)
        {
            if (ModelState.IsValid)
            {
                if (site.countContent >= 0)
                {
                    sitesHandler.Update(site);
                    return RedirectToAction("Index");
                }
            }
            ViewBag.language_id = new SelectList(languagesHandler.All(), "id", "title", site.language_id);
            return View(site);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sites site = sitesHandler.GetById(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            return View(site);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            sitesHandler.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                sitesHandler.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Uspa.Admin/Controllers/UserGroupsController.cs
using System.Net;
using System.Web.Mvc;
using Uspa.Domain.LocalDb;
using Uspa.Domain.Repository.Implementation;
using Uspa.Domain.Repository.Interface;

namespace Uspa.Admin.Controllers
{
    public class UserGroupsController : Controller
    {
        private IUserGroups repository = new UsersGroupsRepository();

        public ActionResult Index()
        {
            return View(repository.All());
        }

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IdentityRoles userGroup = repository.GetById(id);
            if (userGroup == null)
            {
                return HttpNotFound();
            }
            return View(userGroup);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title")] IdentityRoles userGroup)
        {
            if (ModelState.IsValid)
            {
                repository.Add(userGroup);
                return RedirectToAction("Index");
            }

            return View(userGroup);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IdentityRoles userGroup = repository.GetById(id);
            if (userGroup == null)
            {
                return HttpNotFound();
            }
            return View(userGroup);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title")] IdentityRoles userGroup)
        {
            if (ModelState.IsValid)
            {
                repository.Update(userGroup);

                return RedirectToAction("Index");
            }
            return View(userGroup);
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IdentityRoles userGroups = repository.GetById(id);
            if (userGroups == null)
            {
                return HttpNotFound();
            }
            return View(userGroups);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            repository.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

Uspa.Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html class="no-js">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Админ панель</title>

    <!-- Bootstrap -->
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendors/easypiechart/jquery.easy-pie-chart.css" rel="stylesheet" media="screen">
    <link href="~/Content/assets/styles.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="~/Content/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <script src="~/Content/vendors/jquery-1.9.1.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/vendors/easypiechart/jquery.easy-pie-chart.js"></script>
    <script src="~/Content/assets/scripts.js"></script>
    <script>
        $(function() {
            // Easy pie charts
            $('.chart').easyPieChart({animate: 1000});
        });
    </script>
</head>

<body>
           <!--/span-->
 
        <div class="container">
            <div class="row">
                <div class="col-md-offset-5 col-md-3">
                    @RenderBody()
                </div>
            </div>
        </div>

                @RenderSection("scripts", required: false)
</body>

</html>

Uspa.Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity


<!DOCTYPE html>
<html class="no-js">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Админ панель</title>

    <!-- Bootstrap -->
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/vendors/easypiechart/jquery.easy-pie-chart.css" rel="stylesheet" media="screen">
    <link href="~/Content/assets/styles.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="~/Content/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <script src="~/Content/vendors/jquery-1.9.1.min.js"></script>
    <script src="~/Content/vendors/jquery-validation/lib/jquery.form.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/vendors/easypiechart/jquery.easy-pie-chart.js"></script>
    <script src="~/Content/assets/scripts.js"></script>
    <script>
        $(function() {
            // Easy pie charts
            $('.chart').easyPieChart({animate: 1000});
        });
    </script>
</head>

<body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <a class="brand" href="#">Панель управления</a>
                <div class="nav-collapse collapse">
                    <ul class="nav pull-right">

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li>
                @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
            </li>
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    </ul>
}
                    </ul>
     
                    <ul class="nav">
                        <li class="active">
                            <a href="@Url.Action("Index", "Home")">Главная</a>
                        </li>
                        <li class="dropdown">
                            <a href="@Url.Action("Index", "Banners")">
                                Banners 
                            </a>
                        </li>   
                        <li class="dropdown">
                            <a href="@Url.Action("Index", "Menus")" role="button">
                                Menus
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                                Gallery<i class="caret"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Albums", "Index", "Albums", new { area = "" }, null)
                                </li>
                                <li>
                                    @Html.ActionLink("Images", "Index", "Images", new { area = "" }, null)
                                </li>                            
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="@Url.Action("Index", "Sites")" role="button">
                                Sites
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                                Content<i class="caret"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    
                                    @Html.ActionLink("Content", "Index", "Contents", new { area = "" }, null)

                                </li>
                                <li>
                                    @Html.ActionLink("Categories", "Index", "Categories", new { area = "" }, null)
                                </li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                                Users<i class="caret"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Users", "Index", "Users", new { area = "" }, null)
                                </li>
                                <li>
                                    @Html.ActionLink("User groups", "Index", "UserGroups", new { area = "" }, null)
                                </li>
                            </ul>
                        </li>

                    </ul>

                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container-fluid">
        @*<div class="row-fluid">*@
            @*<div class="span3" id="sidebar">
                <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                    <li class="active">
                        <a href="index.html"><i class="icon-chevron-right"></i> Сайт</a>
                    </li>
                    <li>
                        <a href="calendar.html"><i class="icon-chevron-right"></i> Пользователи</a>
                    </li>
                    <li>
                        <a href="../Content/Index"><i class="icon-chevron-right"></i> Материалы</a>
                    </li>
                    <li>
                        <a href="form.html"><i class="icon-chevron-right"></i> Компоненты</a>
                    </li>
                    <li>
                        <a href="tables.html"><i class="icon-chevron-right"></i> Расширения</a>
                    </li>
                    <li>
                        <a href="buttons.html"><i class="icon-chevron-right"></i> Справка</a>
                    </li>
                    <li>
                        <a href="editors.html"><i class="icon-chevron-right"></i> Меню</a>
                    </li>
                    <li>
                        <a href="interface.html"><i class="icon-chevron-right"></i> UI & Interface</a>
                    </li>
                  
                    <li>
                        <a href="#"><span class="badge badge-important pull-right">83</span> Errors</a>
                    </li>
                    <li>
                        <a href="#"><span class="badge badge-warning pull-right">4,231</span> Logs</a>
                    </li>
                </ul>
            </div>*@

            <!--/span-->

            <div class="span12 row-fluid" id="content">
                @RenderBody()

            </div>

        @*</div>*@
        <hr>
        <footer>
            <p>&copy; Администрация морских портов Украины</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>

</html>